#' @title Generate a Number to Set Seed
#'
#' @description This function implements a formula based on current date and time.
#'
#' @return An integer number.
#'
#' @details The number is generated by combining current seconds (S), minutes (Mi), hours (H), days (D), months (Mo), years (Y) and golden ratio (\eqn{\phi}), in the form:
#'
#' \deqn{ Num = (S * Mi + H * D * Mo / D) ^ \phi}
#'
#' @author Mattia Chiesa, Luca Piacentini
#'
#' @examples
#' gen_numb <- DaMiR.goldenDice()
#' set.seed(gen_numb)
#'
#' @export
#'
#'
DaMiR.goldenDice <- function(){

  golden_ratio <- 1.6180339887
  golden_dice <-round((second(Sys.time())*minute(Sys.time())+hour(Sys.time())*day(Sys.time())*month(Sys.time())/year(Sys.time()))^golden_ratio)

  return(golden_dice)
}

#' @title Matrix transposition and replacement of '.' and '-' special characters
#'
#' @description This function transposes matrix and replaces '.' and '-' special characters.
#'
#' @param data Matrix of normalized expression data, i.e. transformed counts by vst or rlog.
#' A log2 transformed expression matrix is also accepted
#'
#' @return Normalized matrix in which each row is a sample and each column is a feature
#'
#' @author Mattia Chiesa, Luca Piacentini
#'
#' @examples
#' data(DaMiR.Data.Ex.Norm)
#' data.transposed <- DaMiR.transpose(DaMiR.Data.Ex.Norm)
#'
#' @export
#'
#'
DaMiR.transpose <- function(data){
  # check arguments
  if (missing(data)) stop("'data' argument must be provided")
  if(!(is.matrix(data))) stop("'data' must be a matrixnumeric")

  data <- as.data.frame(t(data))
  colnames(data) <- gsub(".","__",colnames(data), fixed = TRUE) # replace dots for formulas
  colnames(data) <- gsub("-","_",colnames(data), fixed = TRUE) # replace dashes for formulas
  return(data)
}

